import type { AppDataSnapshot } from "@/types"

const now = new Date().toISOString()
const today = new Date().toISOString().slice(0, 10)
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10)
const lastWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10)

export const demoData: AppDataSnapshot = {
  users: [
    {
      id: "usr-admin",
      fullName: "Amina Nsimba",
      email: "admin@marchervente.app",
      password: "admin123",
      role: "admin",
      isActive: true,
      createdAt: now,
    },
    {
      id: "usr-manager",
      fullName: "Joel Mbuyi",
      email: "gestion@marchervente.app",
      password: "manager123",
      role: "gestionnaire",
      isActive: true,
      createdAt: now,
    },
    {
      id: "usr-seller",
      fullName: "Grace Ilunga",
      email: "vendeur@marchervente.app",
      password: "seller123",
      role: "vendeur",
      isActive: true,
      createdAt: now,
    },
  ],
  clients: [
    {
      id: "cl-001",
      fullName: "Merveille Kanku",
      phone: "+243 997 100 201",
      address: "Matete, Kinshasa",
      notes: "Cliente reguliere avec paiements mobiles.",
      createdAt: now,
    },
    {
      id: "cl-002",
      fullName: "Cedric Kasongo",
      phone: "+243 996 200 302",
      address: "Ngaliema, Kinshasa",
      notes: "Achete surtout des produits secs en volumes.",
      createdAt: now,
    },
    {
      id: "cl-003",
      fullName: "Esperance Kiala",
      phone: "+243 999 300 403",
      address: "Bandalungwa, Kinshasa",
      notes: "Dette active a suivre chaque semaine.",
      createdAt: now,
    },
    {
      id: "cl-004",
      fullName: "Patrick Mbala",
      phone: "+243 995 777 901",
      address: "Masina, Kinshasa",
      notes: "Grossiste avec echeances negociees a 14 jours.",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "pr-001",
      name: "Sac de riz 25kg",
      description: "Riz blanc premium",
      unitPrice: 32,
      stockQuantity: 38,
      status: "active",
      createdAt: now,
    },
    {
      id: "pr-002",
      name: "Bidon d'huile 5L",
      description: "Huile vegetale raffinee",
      unitPrice: 18,
      stockQuantity: 53,
      status: "active",
      createdAt: now,
    },
    {
      id: "pr-003",
      name: "Carton de savon",
      description: "Savon menager en lot",
      unitPrice: 14,
      stockQuantity: 25,
      status: "active",
      createdAt: now,
    },
    {
      id: "pr-004",
      name: "Sucre 50kg",
      description: "Sac de sucre cristallise",
      unitPrice: 44,
      stockQuantity: 16,
      status: "active",
      createdAt: now,
    },
  ],
  sales: [
    {
      id: "sl-001",
      clientId: "cl-003",
      clientName: "Esperance Kiala",
      saleDate: yesterday,
      paymentType: "deposit",
      totalAmount: 100,
      paidAmount: 60,
      remainingAmount: 40,
      notes: "Paiement echelone convenu sur trois passages.",
      createdBy: "Joel Mbuyi",
      debtId: "db-001",
      createdAt: now,
      items: [
        {
          id: "sli-001",
          productId: "pr-001",
          productName: "Sac de riz 25kg",
          quantity: 2,
          unitPrice: 32,
          lineTotal: 64,
        },
        {
          id: "sli-002",
          productId: "pr-002",
          productName: "Bidon d'huile 5L",
          quantity: 2,
          unitPrice: 18,
          lineTotal: 36,
        },
      ],
    },
    {
      id: "sl-002",
      clientId: "cl-001",
      clientName: "Merveille Kanku",
      saleDate: today,
      paymentType: "cash",
      totalAmount: 50,
      paidAmount: 50,
      remainingAmount: 0,
      notes: "Paiement comptant au comptoir.",
      createdBy: "Grace Ilunga",
      createdAt: now,
      items: [
        {
          id: "sli-003",
          productId: "pr-002",
          productName: "Bidon d'huile 5L",
          quantity: 2,
          unitPrice: 18,
          lineTotal: 36,
        },
        {
          id: "sli-004",
          productId: "pr-003",
          productName: "Carton de savon",
          quantity: 1,
          unitPrice: 14,
          lineTotal: 14,
        },
      ],
    },
    {
      id: "sl-003",
      clientId: "cl-004",
      clientName: "Patrick Mbala",
      saleDate: lastWeek,
      paymentType: "credit",
      totalAmount: 120,
      paidAmount: 0,
      remainingAmount: 120,
      notes: "Livraison en gros avec echeance hebdomadaire.",
      createdBy: "Amina Nsimba",
      debtId: "db-002",
      createdAt: now,
      items: [
        {
          id: "sli-005",
          productId: "pr-004",
          productName: "Sucre 50kg",
          quantity: 2,
          unitPrice: 44,
          lineTotal: 88,
        },
        {
          id: "sli-006",
          productId: "pr-001",
          productName: "Sac de riz 25kg",
          quantity: 1,
          unitPrice: 32,
          lineTotal: 32,
        },
      ],
    },
  ],
  debts: [
    {
      id: "db-001",
      saleId: "sl-001",
      clientId: "cl-003",
      clientName: "Esperance Kiala",
      initialAmount: 100,
      totalPaid: 60,
      remainingAmount: 40,
      status: "partial",
      dueDate: today,
      createdAt: now,
    },
    {
      id: "db-002",
      saleId: "sl-003",
      clientId: "cl-004",
      clientName: "Patrick Mbala",
      initialAmount: 120,
      totalPaid: 0,
      remainingAmount: 120,
      status: "unpaid",
      dueDate: today,
      createdAt: now,
    },
  ],
  payments: [
    {
      id: "pay-001",
      debtId: "db-001",
      clientId: "cl-003",
      clientName: "Esperance Kiala",
      paymentDate: yesterday,
      amount: 30,
      method: "cash",
      reference: "ESP-001",
      note: "Premier versement",
      createdBy: "Joel Mbuyi",
      createdAt: now,
    },
    {
      id: "pay-002",
      debtId: "db-001",
      clientId: "cl-003",
      clientName: "Esperance Kiala",
      paymentDate: today,
      amount: 20,
      method: "mobile_money",
      reference: "ESP-002",
      note: "Deuxieme versement",
      createdBy: "Joel Mbuyi",
      createdAt: now,
    },
    {
      id: "pay-003",
      debtId: "db-001",
      clientId: "cl-003",
      clientName: "Esperance Kiala",
      paymentDate: today,
      amount: 10,
      method: "cash",
      reference: "ESP-003",
      note: "Troisieme versement",
      createdBy: "Joel Mbuyi",
      createdAt: now,
    },
  ],
  stockMovements: [
    {
      id: "stk-001",
      productId: "pr-001",
      productName: "Sac de riz 25kg",
      movementType: "out",
      quantity: 2,
      reason: "Vente sl-001",
      referenceId: "sl-001",
      createdAt: now,
    },
    {
      id: "stk-002",
      productId: "pr-002",
      productName: "Bidon d'huile 5L",
      movementType: "out",
      quantity: 2,
      reason: "Vente sl-002",
      referenceId: "sl-002",
      createdAt: now,
    },
    {
      id: "stk-003",
      productId: "pr-001",
      productName: "Sac de riz 25kg",
      movementType: "out",
      quantity: 2,
      reason: "Vente sl-001",
      referenceId: "sl-001",
      createdAt: now,
    },
    {
      id: "stk-004",
      productId: "pr-004",
      productName: "Sucre 50kg",
      movementType: "out",
      quantity: 2,
      reason: "Vente sl-003",
      referenceId: "sl-003",
      createdAt: now,
    },
    {
      id: "stk-005",
      productId: "pr-001",
      productName: "Sac de riz 25kg",
      movementType: "out",
      quantity: 1,
      reason: "Vente sl-003",
      referenceId: "sl-003",
      createdAt: now,
    },
  ],
  auditLogs: [
    {
      id: "log-001",
      action: "SALE_CREATED",
      entityType: "sale",
      entityId: "sl-001",
      actorName: "Joel Mbuyi",
      details: "Vente creee avec dette partielle.",
      createdAt: now,
    },
    {
      id: "log-002",
      action: "PAYMENT_RECORDED",
      entityType: "payment",
      entityId: "pay-003",
      actorName: "Joel Mbuyi",
      details: "Paiement partiel ajoute a la dette db-001.",
      createdAt: now,
    },
    {
      id: "log-003",
      action: "SALE_CREATED",
      entityType: "sale",
      entityId: "sl-003",
      actorName: "Amina Nsimba",
      details: "Vente creee avec dette non payee.",
      createdAt: now,
    },
  ],
}
